version: '3.8'

services:
  # Python ML Service
  ml-service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml_service/static:/app/static
    environment:
      - PYTHONUNBUFFERED=1

  # Go Backend Service
  backend:
    build:
      context: ./dental_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ML_SERVICE_URL=http://ml-service:8000
      - DATABASE_URL=postgresql://user:password@db:5432/dental_db
    depends_on:
      - ml-service
      - db

  # PostgreSQL Database
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080

volumes:
  postgres_data: